name: flare_splash_screen
description: Facilitator for having a Splash screen with a Flare animation until some work has been done for the initialization of the app
version: 4.0.0
homepage: https://github.com/jaumard/flare_splash_screen

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: ">=3.0.2 <4.0.0"

dependencies:

  flare_loading:
    git:
      url: https://github.com/4itworks/flare_loading
  #path: '../flare_loading'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
