name: flare_splash_screen
description: Facilitator for having a Splash screen with a Flare animation until some work has been done for the initialization of the app
version: 4.0.0
homepage: https://github.com/jaumard/flare_splash_screen

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.2.0 <4.0.0"

dependencies:

  flare_loading:
    git:
      url: https://github.com/4itworks/flare_loading.git
      ref: master
  #path: '../flare_loading'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
